### ISSUE TITLE
Tagging the plugin

### ISSUE THREAD

**Issue by AmrutheshC** [phonegap/phonegap-mobile-accessibility#10]
Could you please tag the plugin before the plugin-dependency changes?  I'm still using the old versions(prior to 1.0.0) of cordova-device and others and hence using the accessibility plugins results in compilation errors.

**Comment by shazron** [comment]
Thanks for fixing the issue! I'll work on this.

**Comment by shazron** [comment]
*filing

**Comment by shazron** [comment]
Tagged previous 0.1.2:
```cordova plugin add https://github.com/phonegap/phonegap-mobile-accessibility.git#0.1.2```
