### ISSUE TITLE
Please add package.json

### ISSUE THREAD

**Issue by tuanhai12h** [phonegap/phonegap-mobile-accessibility#22]
Hi team,

The cordova-plugin updated, so the git package must have package.json file.

Please update it soon.

Thanks,
Hanux

**Comment by shazron** [comment]
This requires a package id rename from: com.phonegap.plugin.mobile-accessibility to an npm convention. Perhaps: phonegap-plugin-mobile-accessibility

Crib off this: https://github.com/phonegap/phonegap-plugin-contentsync/blob/master/package.json

**Comment by tuanhai12h** [comment]
Thanks,
I want this plug-in https://github.com/phonegap/phonegap-mobile-accessibility have the package.json file.
Because I using Meteor apps, so all plugin is can not load from local (or I don't know ways to do it)

Hope the owner apps can update it soon.

**Comment by shazron** [comment]
The README already shows you how to add it from the repo.
`cordova plugin add https://github.com/phonegap/phonegap-mobile-accessibility.git`

Please use that for now

**Comment by majornista** [comment]
Should be fixed now.
