### ISSUE TITLE
Publish new version with fix for Issue 20 on npmjs

### ISSUE THREAD

**Issue by elsewhat** [phonegap/phonegap-mobile-accessibility#23]
Hi, 

Could you publish a new version of the plugin on npmjs.com? 
Issue 20 has not been released there https://github.com/phonegap/phonegap-mobile-accessibility/issues/20

We're planning to use the plugin from an app built with phonegap build, and therefore need to use npmjs.com as the source for the plugin

Keep up the good work

**Comment by majornista** [comment]
I've pushed r1.0.1.
