### ISSUE TITLE
Fails to compile with cordova-ios 4.0.0

### ISSUE THREAD

**Issue by kerrishotts** [phonegap/phonegap-mobile-accessibility#26]
CDVMobileAccessibility.m: 183
No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

The fix is easy; replace line 183 with:

```objc
#ifdef __CORDOVA_4_0_0
        [[self webViewEngine] evaluateJavaScript:jsString completionHandler:nil];
#else
        [[self webView] stringByEvaluatingJavaScriptFromString:jsString];
#endif
```

**Comment by majornista** [comment]
Per @shazron https://github.com/phonegap/phonegap-mobile-accessibility/pull/27#issuecomment-164939634, this has been fixed with 71640de using `self.commandDelegate evalJs`. Thanks a ton for your contribution @kerrishotts!
